import localFont from "next/font/local";
import "./globals.css";
import Nav from "./nav/nav";
import Container from "@/components/container";
import LenisCom from "@/components/lenis";
import Footer from "./footer/footer";

// const geistSans = localFont({
// 	src: "./fonts/GeistVF.woff",
// 	variable: "--font-geist-sans",
// 	weight: "100 900",
// });
// const geistMono = localFont({
// 	src: "./fonts/GeistMonoVF.woff",
// 	variable: "--font-geist-mono",
// 	weight: "100 900",
// });
const AzeretMono = localFont({
	src: "./fonts/AzeretMono-Thin.otf",
	variable: "--font-AzeretMono",
	weight: "100 900",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${AzeretMono.className}  antialiased`}>
				<Nav />
				<Container>
					<LenisCom>{children}</LenisCom>
				</Container>
				<Footer />
			</body>
		</html>
	);
}
